#
# Wire
# Copyright (C) 2025 Wire Swiss GmbH
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
# GNU General Public License for more details.
# You should have received a copy of the GNU General Public License
# along with this program. If not, see http://www.gnu.org/licenses/.
#

#demo.user.id = 4db83013-a64a-47aa-91dc-787cd7875b16
demo.user.id = 2078a8fa-65a5-46f8-9740-88f35d0ae76f
#demo.user.client = 45c96c10c6b83405
#demo.user.email = remind-app@wire.com
demo.user.email = sasha-chala-1@wire.com
demo.user.password = Aqa123456!
