/*
 * This source file was generated by the Gradle 'init' task
 */
package com.wire.integrations.jvm

import com.wire.integrations.jvm.config.IsolatedKoinContext
import com.wire.integrations.jvm.service.WireTeamManager
import org.koin.dsl.module

class WireBotSdk {
    constructor(wireBotListener: WireBotListener) {
        val dynamicModule = module {
            single {
                wireBotListener
            }
        }
        IsolatedKoinContext.koinApp.koin.loadModules(listOf(dynamicModule))
        // TODO: probably trigger here the connections to Server-Sent Events and the WebSockets
    }

    fun getTeamManager(): WireTeamManager {
        return IsolatedKoinContext.koinApp.koin.get()
    }

    fun someLibraryMethod(): Boolean {
        return true
    }
}
