/*
 * Wire
 * Copyright (C) 2025 Wire Swiss GmbH
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
 * GNU General Public License for more details.
 * You should have received a copy of the GNU General Public License
 * along with this program. If not, see http://www.gnu.org/licenses/.
 */

package com.wire.integrations.jvm.model

import com.wire.integrations.jvm.config.IsolatedKoinContext
import com.wire.integrations.jvm.exception.WireException
import java.util.UUID

@Suppress("ArrayInDataClass")
sealed interface WireMessage {
    // The message id, auto-generated by the SDK while sending, useful to later edit/delete it
    val id: UUID

    // The conversation where this message is sent/received
    val conversationId: QualifiedId

    // The user/apps that sent this message, useful when receiving messages, ignored when sending
    val sender: QualifiedId

    sealed interface Item

    sealed interface Ephemeral {
        val expiresAfterMillis: Long?
    }

    @JvmRecord
    data class Text @JvmOverloads constructor(
        override val id: UUID,
        override val conversationId: QualifiedId,
        override val sender: QualifiedId,
        override val expiresAfterMillis: Long? = null,
        val text: String,
        val quotedMessageId: UUID? = null,
        val quotedMessageSha256: ByteArray? = null,
        val mentions: List<Mention> = emptyList(),
        val linkPreviews: List<LinkPreview> = emptyList()
    ) : WireMessage, Item, Ephemeral {
        companion object {
            /**
             * Creates a basic text message with minimal required parameters.
             *
             * @param conversationId The qualified ID of the conversation
             * @param text The text content of the message
             * @param mentions List of [Mention] included in the text
             * @return A new Text message with a random UUID
             */
            @JvmStatic
            fun create(
                conversationId: QualifiedId,
                text: String,
                mentions: List<Mention> = listOf(),
                expiresAfterMillis: Long? = null
            ): Text {
                return Text(
                    id = UUID.randomUUID(),
                    conversationId = conversationId,
                    sender = IsolatedKoinContext.getApplicationQualifiedId(),
                    text = text,
                    mentions = mentions,
                    expiresAfterMillis = expiresAfterMillis
                )
            }
        }
    }

    @JvmRecord
    data class Mention @JvmOverloads constructor(
        val userId: QualifiedId,
        val offset: Int = 0,
        val length: Int = 0
    )

    @JvmRecord
    data class LinkPreview @JvmOverloads constructor(
        val summary: String? = null,
        val title: String? = null,
        val url: String? = null,
        val urlOffset: Int = 0,
        val mimeType: String? = null,
        val name: String? = null,
        val size: Long = 0
    )

    @JvmRecord
    data class Asset @JvmOverloads constructor(
        override val id: UUID,
        override val conversationId: QualifiedId,
        override val sender: QualifiedId,
        override val expiresAfterMillis: Long? = null,
        val sizeInBytes: Long,
        val name: String? = null,
        val mimeType: String,
        val metadata: AssetMetadata? = null,
        val remoteData: AssetMetadata.RemoteData? = null
    ) : WireMessage, Ephemeral {
        sealed class AssetMetadata {
            data class Image(val width: Int, val height: Int) : AssetMetadata()

            data class Video(
                val width: Int?,
                val height: Int?,
                val durationMs: Long?
            ) : AssetMetadata()

            data class Audio(
                val durationMs: Long?,
                val normalizedLoudness: ByteArray?
            ) : AssetMetadata()

            enum class MessageEncryptionAlgorithm { AES_CBC, AES_GCM }

            @JvmRecord
            data class RemoteData @JvmOverloads constructor(
                val otrKey: ByteArray,
                val sha256: ByteArray,
                val assetId: String,
                val assetToken: String? = null,
                val assetDomain: String,
                val encryptionAlgorithm: MessageEncryptionAlgorithm? = null
            )
        }
    }

    @JvmRecord
    data class Composite(
        override val id: UUID,
        override val conversationId: QualifiedId,
        override val sender: QualifiedId,
        val items: List<Item>
    ) : WireMessage {
        @JvmRecord
        data class Button @JvmOverloads constructor(
            val text: String,
            val id: String = UUID.randomUUID().toString()
        ) : Item

        companion object {
            /**
             * Creates a Composite message with a single text first, followed by a list of buttons.
             *
             * @param conversationId The qualified ID of the conversation
             * @param text The text content of the message
             * @param buttonList The list of buttons to be selected
             * @return A new Composite message
             */
            @JvmStatic
            fun create(
                conversationId: QualifiedId,
                text: String,
                buttonList: List<Button>
            ): Composite {
                val textItem = Text.create(
                    conversationId = conversationId,
                    text = text
                )

                return Composite(
                    id = UUID.randomUUID(),
                    conversationId = conversationId,
                    sender = IsolatedKoinContext.getApplicationQualifiedId(),
                    items = listOf(textItem) + buttonList
                )
            }
        }
    }

    /**
     * Notifies the author of a [Composite] message that a user has
     * selected one of its buttons.
     * @see Composite
     * @see ButtonActionConfirmation
     */
    @JvmRecord
    data class ButtonAction(
        override val id: UUID,
        override val conversationId: QualifiedId,
        override val sender: QualifiedId,
        /**
         * The ID of the original composite message.
         */
        val referencedMessageId: String,
        /**
         * ID of the button that was selected.
         */
        val buttonId: String
    ) : WireMessage

    /**
     * Message sent by the author of a [Composite] to
     * notify which button should be marked as selected.
     * For example, after we send [ButtonAction], the author might reply
     * with [ButtonActionConfirmation] to confirm that the button event was processed.
     * @see ButtonAction
     * @see Composite
     */
    @JvmRecord
    data class ButtonActionConfirmation(
        override val id: UUID,
        override val conversationId: QualifiedId,
        override val sender: QualifiedId,
        /**
         * ID fo the original composite message
         */
        val referencedMessageId: String,
        /**
         * ID of the selected button. Null if no button should be marked as selected.
         */
        val buttonId: String?
    ) : WireMessage

    @JvmRecord
    data class Knock(
        override val id: UUID,
        override val conversationId: QualifiedId,
        override val sender: QualifiedId,
        override val expiresAfterMillis: Long? = null,
        val hotKnock: Boolean
    ) : WireMessage, Ephemeral {
        companion object {
            /**
             * Creates a basic Knock message with minimal required parameters.
             *
             * @param conversationId The qualified ID of the conversation
             * @param hotKnock
             * @return A new Knock message with a random UUID
             */
            @JvmStatic
            fun create(
                conversationId: QualifiedId,
                hotKnock: Boolean,
                expiresAfterMillis: Long? = null
            ): Knock {
                return Knock(
                    id = UUID.randomUUID(),
                    conversationId = conversationId,
                    sender = IsolatedKoinContext.getApplicationQualifiedId(),
                    hotKnock = hotKnock,
                    expiresAfterMillis = expiresAfterMillis
                )
            }
        }
    }

    @JvmRecord
    data class Location @JvmOverloads constructor(
        override val id: UUID,
        override val conversationId: QualifiedId,
        override val sender: QualifiedId,
        override val expiresAfterMillis: Long? = null,
        val latitude: Float,
        val longitude: Float,
        val name: String? = null,
        val zoom: Int = 0
    ) : WireMessage, Ephemeral {
        companion object {
            /**
             * Creates a basic Location message with minimal required parameters.
             *
             * @param conversationId The qualified ID of the conversation
             * @param latitude The Latitude of the Location
             * @param longitude The Longitude of the Location
             * @param name In case the location contains a name
             * @param zoom The zoom value to be used when displaying the location on a map
             * @return A new Location message with a random UUID
             */
            @Suppress("LongParameterList")
            @JvmStatic
            fun create(
                conversationId: QualifiedId,
                latitude: Float,
                longitude: Float,
                name: String? = null,
                zoom: Int = 0,
                expiresAfterMillis: Long? = null
            ): Location {
                return Location(
                    id = UUID.randomUUID(),
                    conversationId = conversationId,
                    sender = IsolatedKoinContext.getApplicationQualifiedId(),
                    latitude = latitude,
                    longitude = longitude,
                    name = name,
                    zoom = zoom,
                    expiresAfterMillis = expiresAfterMillis
                )
            }
        }
    }

    @JvmRecord
    data class Deleted(
        override val id: UUID,
        override val conversationId: QualifiedId,
        override val sender: QualifiedId,
        val messageId: String
    ) : WireMessage {
        companion object {
            /**
             * Creates a basic Deleted message (a message was deleted).
             *
             * @param conversationId The qualified ID of the conversation
             * @param messageId The ID of the deleted message
             * @return A new Deleted message with a random UUID
             */
            @JvmStatic
            fun create(
                conversationId: QualifiedId,
                messageId: String
            ): Deleted =
                Deleted(
                    id = UUID.randomUUID(),
                    conversationId = conversationId,
                    sender = IsolatedKoinContext.getApplicationQualifiedId(),
                    messageId = messageId
                )
        }
    }

    @JvmRecord
    data class Receipt(
        override val id: UUID,
        override val conversationId: QualifiedId,
        override val sender: QualifiedId,
        val type: Type,
        val messageIds: List<String>
    ) : WireMessage {
        enum class Type {
            DELIVERED,
            READ
        }

        companion object {
            /**
             * Creates a basic Receipt message.
             *
             * @param conversationId The qualified ID of the conversation
             * @param type The type of receipt (DELIVERED or READ)
             * @param messages The related message IDs
             * @return A new Receipt message with a random UUID
             */
            @JvmStatic
            fun create(
                conversationId: QualifiedId,
                type: Type,
                messages: List<String> = listOf()
            ): Receipt =
                Receipt(
                    id = UUID.randomUUID(),
                    conversationId = conversationId,
                    sender = IsolatedKoinContext.getApplicationQualifiedId(),
                    type = type,
                    messageIds = messages
                )
        }
    }

    @JvmRecord
    data class TextEdited @JvmOverloads constructor(
        override val id: UUID,
        override val conversationId: QualifiedId,
        override val sender: QualifiedId? = null,
        val newContent: String,
        val newLinkPreviews: List<LinkPreview> = listOf(),
        val newMentions: List<Mention> = listOf()
    ) : WireMessage {
        companion object {
            /**
             * Creates a TextEdited message with minimal required parameters.
             *
             * Usage from Kotlin:
             * ```kotlin
             * val message = TextEdited.create(
             *                  <optional> messageId,
             *                  conversationId,
             *                  "Edited text",
             *                  mentionsList
             *               )
             * ```
             *
             * Usage from Java:
             * ```java
             * Text message = TextEdited.Companion.create(
             *                   <optional> messageId,
             *                   conversationId,
             *                   "Edited text",
             *                   mentionsList
             *                );
             * ```
             *
             * @param conversationId The qualified ID of the conversation
             * @param text The text content of the message
             * @param mentions List of [Mention] included in the text
             * @return A new TextEdited message with either a received ID or a random UUID
             */
            @JvmStatic
            fun create(
                id: UUID = UUID.randomUUID(),
                conversationId: QualifiedId,
                text: String,
                mentions: List<Mention> = listOf()
            ): Text {
                return Text(
                    id = id,
                    conversationId = conversationId,
                    text = text,
                    mentions = mentions
                )
            }
        }
    }

    data object Ignored : WireMessage {
        override val id: UUID
            get() = throw WireException.InvalidParameter("Ignored message, no ID")
        override val conversationId: QualifiedId
            get() = throw WireException.InvalidParameter("Ignored message, no conversation")
        override val sender: QualifiedId
            get() = throw WireException.InvalidParameter("Ignored message, no sender")
    }

    data object Unknown : WireMessage {
        override val id: UUID
            get() = throw WireException.InvalidParameter("Unknown message, no ID")
        override val conversationId: QualifiedId
            get() = throw WireException.InvalidParameter("Unknown message, no conversation")
        override val sender: QualifiedId
            get() = throw WireException.InvalidParameter("Unknown message, no sender")
    }
}
