name: Docs

on:
  workflow_dispatch:
  pull_request:
    paths:
      - 'docs/**'

jobs:
  docs-verification:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-java@v5
        with:
          distribution: 'zulu'
          java-version: '17'

      - name: Setup Nix
        uses: cachix/install-nix-action@v31

      - name: Clone wire-docs and build
        run: |
          git clone --branch main https://github.com/wireapp/wire-docs.git wire-docs
          cd wire-docs
          
          CURRENT_REPO_URL="https://github.com/${GITHUB_REPOSITORY}.git"
          
          if [ -n "$GITHUB_HEAD_REF" ]; then
              CURRENT_BRANCH="$GITHUB_HEAD_REF"
          else
              CURRENT_BRANCH="${GITHUB_REF#refs/heads/}"
          fi
          
          sed -i "s|url = https://github.com/wireapp/wire-apps-jvm-sdk.git|url = ${CURRENT_REPO_URL}|g" .gitmodules
          sed -i "s|branch = main|branch = ${CURRENT_BRANCH}|g" .gitmodules
          
          cat .gitmodules
          make build
