name: Test README Update

on:
  workflow_dispatch: # allows manual triggering

jobs:
  test-readme:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5

      - name: Set fake release version
        run: echo "VERSION=9.9.9" >> $GITHUB_ENV

      - name: Update README.md (dry-run)
        run: |
          echo "Updating README.md with version $VERSION (dry-run)"

          # Update Gradle snippet
          sed "s|implementation(\"com\\.wire:wire-apps-jvm-sdk:[0-9.]\+\")|implementation(\"com.wire:wire-apps-jvm-sdk:${VERSION}\")|g" README.md > README.tmp
          mv README.tmp README.md

          # Update Maven snippet
          sed "s|<version>[0-9.]\+</version>|<version>${VERSION}</version>|g" README.md > README.tmp
          mv README.tmp README.md

          # Show updated README.md in logs
          cat README.md
